/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    schools: School;
    homepage: Homepage;
    'privacy-policy': PrivacyPolicy;
    'cookie-policy': CookiePolicy;
    'chi-siamo': ChiSiamo;
    teachers: Teacher;
    events: Event;
    projects: Project;
    'calendar-days': CalendarDay;
    menu: Menu;
    documents: Document;
    testimonials: Testimonial;
    communications: Communication;
    'email-subscribers': EmailSubscriber;
    'parent-registrations': ParentRegistration;
    'child-updates': ChildUpdate;
    'parent-appointments': ParentAppointment;
    articles: Article;
    media: Media;
    gallery: Gallery;
    children: Child;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    schools: SchoolsSelect<false> | SchoolsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'privacy-policy': PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
    'cookie-policy': CookiePolicySelect<false> | CookiePolicySelect<true>;
    'chi-siamo': ChiSiamoSelect<false> | ChiSiamoSelect<true>;
    teachers: TeachersSelect<false> | TeachersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'calendar-days': CalendarDaysSelect<false> | CalendarDaysSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    communications: CommunicationsSelect<false> | CommunicationsSelect<true>;
    'email-subscribers': EmailSubscribersSelect<false> | EmailSubscribersSelect<true>;
    'parent-registrations': ParentRegistrationsSelect<false> | ParentRegistrationsSelect<true>;
    'child-updates': ChildUpdatesSelect<false> | ChildUpdatesSelect<true>;
    'parent-appointments': ParentAppointmentsSelect<false> | ParentAppointmentsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    children: ChildrenSelect<false> | ChildrenSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schools".
 */
export interface School {
  id: string;
  /**
   * Il nome completo della scuola
   */
  name: string;
  /**
   * Identificatore univoco per URL (es: scuola-primaria-roma)
   */
  slug: string;
  /**
   * Se disattivata, il sito della scuola non sarà accessibile
   */
  isActive?: boolean | null;
  /**
   * Logo della scuola
   */
  logo?: (string | null) | Media;
  /**
   * Colori utilizzati quando il tema chiaro è attivo
   */
  lightTheme?: {
    /**
     * Colore principale del testo (tema chiaro)
     */
    textPrimary?: string | null;
    /**
     * Colore secondario del testo (tema chiaro)
     */
    textSecondary?: string | null;
    /**
     * Colore di sfondo primario (tema chiaro)
     */
    backgroundPrimary?: string | null;
    /**
     * Colore di sfondo secondario (tema chiaro)
     */
    backgroundSecondary?: string | null;
  };
  /**
   * Colori utilizzati quando il tema scuro è attivo
   */
  darkTheme?: {
    /**
     * Colore principale del testo (tema scuro)
     */
    textPrimary?: string | null;
    /**
     * Colore secondario del testo (tema scuro)
     */
    textSecondary?: string | null;
    /**
     * Colore di sfondo primario (tema scuro)
     */
    backgroundPrimary?: string | null;
    /**
     * Colore di sfondo secondario (tema scuro)
     */
    backgroundSecondary?: string | null;
  };
  primaryColor?: string | null;
  secondaryColor?: string | null;
  backgroundPrimaryColor?: string | null;
  backgroundSecondaryColor?: string | null;
  contactInfo?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  /**
   * Scegli quali funzionalità mostrare nel sito della tua scuola
   */
  featureVisibility?: {
    showChiSiamo?: boolean | null;
    showBlog?: boolean | null;
    showEvents?: boolean | null;
    showProjects?: boolean | null;
    showCalendar?: boolean | null;
    showMenu?: boolean | null;
    showDocuments?: boolean | null;
    showCommunications?: boolean | null;
    showParentsArea?: boolean | null;
  };
  /**
   * Informazioni sul piano di abbonamento
   */
  subscription?: {
    plan?: ('starter' | 'professional' | 'enterprise') | null;
    isTrial?: boolean | null;
    /**
     * Data di scadenza del piano corrente
     */
    expiresAt?: string | null;
    stripeCustomerId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Scuola a cui appartiene questo file
   */
  school?: (string | null) | School;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Qui puoi configurare lo stile della tua homepage. Puoi creare più homepage diverse e attivarle una per volta. Se non imposti alcuna homepage personalizzata, verrà utilizzata una versione di default.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  /**
   * Scuola a cui appartiene questa configurazione
   */
  school?: (string | null) | School;
  /**
   * Se disattivata, la testimonianza non sarà visibile nel frontend
   */
  isActive?: boolean | null;
  /**
   * Dai un nome a questa homepage
   */
  name?: string | null;
  /**
   * Personalizza l'hero di default della pagina
   */
  heroSettings?: {
    /**
     * Se disabilitato, la copertina non verrà mostrata (utile se usi un immagini personalizzate)
     */
    showHero?: boolean | null;
    /**
     * Titolo che appare nella copertina
     */
    title?: string | null;
    /**
     * Testo che appare sotto il titolo nell'hero
     */
    subtitle?: string | null;
    /**
     * Se abilitato, la copertina occuperà l'intera altezza dello schermo
     */
    fullHeight?: boolean | null;
    /**
     * Immagine opzionale per lo sfondo dell'hero
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Se abilitato, l'immagine di sfondo avrà un effetto parallax durante lo scroll
     */
    parallax?: boolean | null;
    /**
     * Se abilitato, aggiunge un overlay gradiente sopra l'immagine per migliorare la leggibilità del testo
     */
    gradientOverlay?: boolean | null;
    /**
     * Aggiungi un divisore decorativo in fondo alla copertina
     */
    bottomDivider?: {
      enabled?: boolean | null;
      style?:
        | (
            | 'wave'
            | 'wave-brush'
            | 'waves'
            | 'zigzag'
            | 'triangle'
            | 'triangle-asymmetric'
            | 'curve'
            | 'curve-asymmetric'
            | 'tilt'
            | 'arrow'
            | 'split'
            | 'clouds'
            | 'mountains'
          )
        | null;
      /**
       * Altezza del divisore in pixel (30-300)
       */
      height?: number | null;
      flip?: boolean | null;
      invert?: boolean | null;
    };
  };
  /**
   * Aggiungi sezioni personalizzate come call-to-action, team cards, feature grids, ecc.
   */
  blocks?:
    | (
        | {
            backgroundColor?: string | null;
            /**
             * Titolo principale con effetto gradiente animato
             */
            title: string;
            /**
             * Testo secondario con animazione blur
             */
            subtitle?: string | null;
            /**
             * Se attivo, l'hero occuperà l'intera altezza dello schermo
             */
            fullHeight?: boolean | null;
            /**
             * Immagine opzionale per lo sfondo dell'hero
             */
            backgroundImage?: (string | null) | Media;
            /**
             * Se abilitato, l'immagine di sfondo avrà un effetto parallax durante lo scroll
             */
            parallax?: boolean | null;
            /**
             * Se abilitato, aggiunge un overlay gradiente sopra l'immagine per migliorare la leggibilità del testo
             */
            gradientOverlay?: boolean | null;
            buttons?:
              | {
                  text: string;
                  href: string;
                  variant?: ('default' | 'destructive' | 'outline' | 'link') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Aggiungi un divisore decorativo in cima all'hero
             */
            topDivider?: {
              enabled?: boolean | null;
              style?:
                | (
                    | 'wave'
                    | 'wave-brush'
                    | 'waves'
                    | 'zigzag'
                    | 'triangle'
                    | 'triangle-asymmetric'
                    | 'curve'
                    | 'curve-asymmetric'
                    | 'tilt'
                    | 'arrow'
                    | 'split'
                    | 'clouds'
                    | 'mountains'
                  )
                | null;
              /**
               * Altezza del divisore in pixel (30-300)
               */
              height?: number | null;
              flip?: boolean | null;
              invert?: boolean | null;
            };
            /**
             * Aggiungi un divisore decorativo in fondo all'hero
             */
            bottomDivider?: {
              enabled?: boolean | null;
              style?:
                | (
                    | 'wave'
                    | 'wave-brush'
                    | 'waves'
                    | 'zigzag'
                    | 'triangle'
                    | 'triangle-asymmetric'
                    | 'curve'
                    | 'curve-asymmetric'
                    | 'tilt'
                    | 'arrow'
                    | 'split'
                    | 'clouds'
                    | 'mountains'
                  )
                | null;
              /**
               * Altezza del divisore in pixel (30-300)
               */
              height?: number | null;
              flip?: boolean | null;
              invert?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            backgroundColor?: string | null;
            title?: string | null;
            limit: number;
            showViewAll?: boolean | null;
            featuredOnly?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            backgroundColor?: string | null;
            title: string;
            subtitle?: string | null;
            image?: (string | null) | Media;
            buttons?:
              | {
                  text: string;
                  href: string;
                  variant?: ('default' | 'secondary' | 'outline' | 'ghost') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            backgroundColor?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            backgroundColor?: string | null;
            title?: string | null;
            columns?: ('2' | '3' | '4') | null;
            cards?:
              | {
                  title: string;
                  description?: string | null;
                  image?: (string | null) | Media;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardGrid';
          }
        | {
            backgroundColor?: string | null;
            /**
             * Es: "Documenti Utili", "Moduli da scaricare"
             */
            title?: string | null;
            description?: string | null;
            files?:
              | {
                  /**
                   * PDF, DOC, XLS, o altri documenti
                   */
                  file: string | Media;
                  /**
                   * Se vuoto, usa il nome del file
                   */
                  title?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'fileDownload';
          }
        | {
            backgroundColor?: string | null;
            /**
             * Seleziona una galleria esistente da mostrare
             */
            gallery: string | Gallery;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            backgroundColor?: string | null;
            /**
             * Es: "Ultime Notizie", "Articoli in Evidenza"
             */
            title?: string | null;
            /**
             * Quanti articoli mostrare (max 12)
             */
            limit: number;
            /**
             * Mostra un pulsante per andare alla pagina blog completa
             */
            showViewAll?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'articleList';
          }
        | {
            backgroundColor?: string | null;
            /**
             * Es: "Prossimi Eventi", "Eventi della Scuola"
             */
            title?: string | null;
            /**
             * Quanti eventi mostrare (max 12)
             */
            limit: number;
            /**
             * Scegli quali eventi mostrare in base alla data
             */
            filter?: ('all' | 'upcoming' | 'past') | null;
            /**
             * Mostra un pulsante per andare alla pagina eventi completa
             */
            showViewAll?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventList';
          }
        | {
            backgroundColor?: string | null;
            /**
             * Es: "I Nostri Progetti", "Progetti della Scuola"
             */
            title?: string | null;
            /**
             * Quanti progetti mostrare (max 12)
             */
            limit: number;
            /**
             * Mostra un pulsante per andare alla pagina progetti completa
             */
            showViewAll?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectList';
          }
        | {
            backgroundColor?: string | null;
            /**
             * Es: "Comunicazioni Importanti", "Avvisi"
             */
            title?: string | null;
            /**
             * Quante comunicazioni mostrare (max 20)
             */
            limit: number;
            /**
             * Seleziona le priorità da mostrare (se vuoto, mostra tutte)
             */
            priorityFilter?: ('low' | 'normal' | 'high' | 'urgent')[] | null;
            /**
             * Mostra un pulsante per andare alla pagina comunicazioni completa
             */
            showViewAll?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'communications';
          }
        | {
            backgroundColor?: string | null;
            /**
             * Es: "Il Nostro Team", "I Nostri Insegnanti"
             */
            title?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'teacherList';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: string;
  /**
   * Scuola a cui appartiene questa galleria
   */
  school?: (string | null) | School;
  /**
   * Nome identificativo della galleria
   */
  title: string;
  /**
   * Breve descrizione della galleria (opzionale)
   */
  description?: string | null;
  /**
   * Aggiungi le immagini alla galleria
   */
  images?:
    | {
        image: string | Media;
        /**
         * Testo descrittivo per l'immagine (opzionale)
         */
        caption?: string | null;
        /**
         * Numero per ordinare le immagini (più basso = prima)
         */
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Specifica a quale contenuto è collegata questa galleria (opzionale)
   */
  linkedTo?: {
    type?: ('none' | 'article' | 'page' | 'event') | null;
    article?: (string | null) | Article;
    event?: (string | null) | Event;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  /**
   * Scuola a cui appartiene questo articolo
   */
  school?: (string | null) | School;
  title: string;
  cover?: (string | null) | Media;
  /**
   * Se abilitato, aggiunge un overlay gradiente sopra l'immagine di copertina per migliorare la leggibilità del testo nell'hero
   */
  gradientOverlay?: boolean | null;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (string | null) | User;
  publishedAt?: string | null;
  /**
   * Collega una galleria di immagini a questo articolo (opzionale)
   */
  gallery?: (string | null) | Gallery;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Amministratore: gestisce la propria scuola | Editor: può modificare contenuti | Genitore: area riservata
   */
  role?: ('super-admin' | 'school-admin' | 'editor' | 'parent') | null;
  /**
   * Scuole di appartenenza
   */
  schools?: (string | School)[] | null;
  /**
   * Bambini associati a questo genitore
   */
  children?: (string | Child)[] | null;
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "children".
 */
export interface Child {
  id: string;
  /**
   * Scuola a cui è iscritto il bambino
   */
  school?: (string | null) | School;
  firstName: string;
  lastName: string;
  fullName?: string | null;
  dateOfBirth?: string | null;
  /**
   * Es: "1A", "Sezione Azzurra", ecc.
   */
  classroom: string;
  /**
   * Foto del bambino
   */
  photo?: (string | null) | Media;
  enrollmentDate?: string | null;
  /**
   * Note visibili solo alla scuola, non ai genitori
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  /**
   * Scuola a cui appartiene questo evento
   */
  school?: (string | null) | School;
  title: string;
  date: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  location?: string | null;
  /**
   * Costo dell'evento (es. "15€" o "Gratuito")
   */
  cost?: string | null;
  cover?: (string | null) | Media;
  /**
   * Se abilitato, aggiunge un overlay gradiente sopra l'immagine di copertina per migliorare la leggibilità del testo nell'hero
   */
  gradientOverlay?: boolean | null;
  /**
   * Collega una galleria di immagini a questo evento (opzionale)
   */
  gallery?: (string | null) | Gallery;
  /**
   * Se abilitato, verrà creata automaticamente una entry nel calendario collegata a questo evento
   */
  addToCalendar?: boolean | null;
  /**
   * Se abilitato, verrà creata automaticamente una comunicazione per notificare questo evento
   */
  sendCommunication?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configura i contenuti della pagina Privacy Policy
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy".
 */
export interface PrivacyPolicy {
  id: string;
  /**
   * Scuola a cui appartiene questa configurazione
   */
  school?: (string | null) | School;
  /**
   * Se disattivata, la testimonianza non sarà visibile nel frontend
   */
  isActive?: boolean | null;
  /**
   * Dai un nome a questa versione della pagina Privacy Policy
   */
  name?: string | null;
  /**
   * Testo principale
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configura i contenuti della pagina Cookie Policy
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-policy".
 */
export interface CookiePolicy {
  id: string;
  /**
   * Scuola a cui appartiene questa configurazione
   */
  school?: (string | null) | School;
  /**
   * Se disattivata, la testimonianza non sarà visibile nel frontend
   */
  isActive?: boolean | null;
  /**
   * Dai un nome a questa versione della pagina Cookie Policy
   */
  name?: string | null;
  /**
   * Testo principale
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configura i contenuti della pagina Chi Siamo
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chi-siamo".
 */
export interface ChiSiamo {
  id: string;
  /**
   * Scuola a cui appartiene questa configurazione
   */
  school?: (string | null) | School;
  /**
   * Se disattivata, la testimonianza non sarà visibile nel frontend
   */
  isActive?: boolean | null;
  /**
   * Dai un nome a questa versione della pagina Chi Siamo
   */
  name?: string | null;
  /**
   * Personalizza l'hero di default della pagina
   */
  heroSettings?: {
    /**
     * Se disabilitato, la copertina non verrà mostrata (utile se usi un immagini personalizzate)
     */
    showHero?: boolean | null;
    /**
     * Titolo che appare nella copertina
     */
    title?: string | null;
    /**
     * Testo che appare sotto il titolo nell'hero
     */
    subtitle?: string | null;
    /**
     * Se abilitato, la copertina occuperà l'intera altezza dello schermo
     */
    fullHeight?: boolean | null;
    /**
     * Immagine opzionale per lo sfondo dell'hero
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Se abilitato, l'immagine di sfondo avrà un effetto parallax durante lo scroll
     */
    parallax?: boolean | null;
    /**
     * Se abilitato, aggiunge un overlay gradiente sopra l'immagine per migliorare la leggibilità del testo
     */
    gradientOverlay?: boolean | null;
    /**
     * Aggiungi un divisore decorativo in fondo alla copertina
     */
    bottomDivider?: {
      enabled?: boolean | null;
      style?:
        | (
            | 'wave'
            | 'wave-brush'
            | 'waves'
            | 'zigzag'
            | 'triangle'
            | 'triangle-asymmetric'
            | 'curve'
            | 'curve-asymmetric'
            | 'tilt'
            | 'arrow'
            | 'split'
            | 'clouds'
            | 'mountains'
          )
        | null;
      /**
       * Altezza del divisore in pixel (30-300)
       */
      height?: number | null;
      flip?: boolean | null;
      invert?: boolean | null;
    };
  };
  /**
   * Testo principale che appare dopo la copertina
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Configura la sezione con la lista degli insegnanti
   */
  teachersSection?: {
    /**
     * Se abilitato, verrà mostrata la lista degli insegnanti della scuola
     */
    enabled?: boolean | null;
    /**
     * Titolo della sezione insegnanti
     */
    title?: string | null;
    /**
     * Sottotitolo opzionale per la sezione insegnanti
     */
    subtitle?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers".
 */
export interface Teacher {
  id: string;
  /**
   * Scuola a cui appartiene questa testimonianza
   */
  school?: (string | null) | School;
  name: string;
  /**
   * Es: Coordinatore, Insegnante di Matematica
   */
  role?: string | null;
  subject?: string | null;
  email?: string | null;
  bio?: string | null;
  photo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  /**
   * Scuola a cui appartiene questo progetto
   */
  school?: (string | null) | School;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cover?: (string | null) | Media;
  /**
   * Se abilitato, aggiunge un overlay gradiente sopra l'immagine di copertina per migliorare la leggibilità del testo nell'hero
   */
  gradientOverlay?: boolean | null;
  /**
   * Collega una galleria di immagini a questo progetto (opzionale)
   */
  gallery?: (string | null) | Gallery;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-days".
 */
export interface CalendarDay {
  id: string;
  /**
   * Scuola a cui appartiene questo evento del calendario
   */
  school?: (string | null) | School;
  title: string;
  description?: string | null;
  type: 'holiday' | 'closure' | 'event' | 'trip';
  /**
   * Costo dell'evento (es. "15€" o "Gratuito")
   */
  cost?: string | null;
  /**
   * Collega un evento per maggiori dettagli
   */
  linkedEvent?: (string | null) | Event;
  startDate: string;
  /**
   * Lasciare vuoto se è un singolo giorno
   */
  endDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestisci i menù stagionali della mensa
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: string;
  /**
   * Scuola a cui appartiene questo menù
   */
  school?: (string | null) | School;
  /**
   * Nome del menù (es. "Menù Autunno 2025", "Menù Inverno 2025")
   */
  name: string;
  /**
   * Solo il menù attivo sarà visualizzato sul sito. Può esserci solo un menù attivo alla volta.
   */
  isActive?: boolean | null;
  /**
   * Data di inizio validità
   */
  validFrom?: string | null;
  /**
   * Data di fine validità
   */
  validTo?: string | null;
  week1?: {
    lunedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    martedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    mercoledì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    giovedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    venerdì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Note o variazioni specifiche per la settimana 1 (opzionale)
     */
    notes?: string | null;
  };
  week2?: {
    lunedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    martedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    mercoledì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    giovedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    venerdì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Note o variazioni specifiche per la settimana 2 (opzionale)
     */
    notes?: string | null;
  };
  week3?: {
    lunedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    martedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    mercoledì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    giovedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    venerdì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Note o variazioni specifiche per la settimana 3 (opzionale)
     */
    notes?: string | null;
  };
  week4?: {
    lunedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    martedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    mercoledì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    giovedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    venerdì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Note o variazioni specifiche per la settimana 4 (opzionale)
     */
    notes?: string | null;
  };
  /**
   * Note generali valide per tutto il menù (es. informazioni sugli allergeni)
   */
  generalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestisci le sezioni di documenti scaricabili
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  /**
   * Scuola a cui appartiene questo documento
   */
  school?: (string | null) | School;
  /**
   * Titolo della sezione che raggruppa questi documenti (es: "Modulistica", "Regolamenti")
   */
  title: string;
  /**
   * Breve descrizione della sezione (opzionale)
   */
  description?: string | null;
  /**
   * Aggiungi uno o più documenti per questa sezione
   */
  files: {
    /**
     * PDF, DOC, XLS, o altri documenti
     */
    file: string | Media;
    /**
     * Nome descrittivo del documento
     */
    title: string;
    /**
     * Breve descrizione del contenuto (opzionale)
     */
    description?: string | null;
    /**
     * Es: "v1.2", "Anno Scolastico 2024/25"
     */
    version?: string | null;
    /**
     * Se attivo, questo documento verrà mostrato nella sezione "In evidenza"
     */
    featured?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Numero per ordinare le sezioni (più basso = prima)
   */
  order?: number | null;
  /**
   * Se attivo, solo gli utenti autenticati potranno scaricare questi file
   */
  requiresAuth?: boolean | null;
  /**
   * Data in cui il documento è stato pubblicato (opzionale)
   */
  publishedAt?: string | null;
  /**
   * Data dopo la quale il documento non sarà più visibile (opzionale)
   */
  expiresAt?: string | null;
  seo?: {
    /**
     * Titolo per i motori di ricerca (se vuoto, usa il titolo del documento)
     */
    metaTitle?: string | null;
    /**
     * Descrizione per i motori di ricerca (max 160 caratteri)
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  /**
   * Scuola a cui appartiene questa testimonianza
   */
  school?: (string | null) | School;
  /**
   * Se non approvata, la testimonianza non sarà visibile nel frontend. Solo gli admin possono approvare.
   */
  approved?: boolean | null;
  /**
   * Se disattivata, la testimonianza non sarà visibile nel frontend
   */
  isActive?: boolean | null;
  /**
   * Nome completo della persona che ha rilasciato la testimonianza
   */
  authorName: string;
  /**
   * Es: Genitore, Ex Studente, Insegnante, ecc.
   */
  role?: string | null;
  /**
   * Foto dell'autore (opzionale)
   */
  photo?: (string | null) | Media;
  /**
   * Testo della testimonianza
   */
  content: string;
  /**
   * Valutazione da 1 a 5 stelle (opzionale)
   */
  rating?: number | null;
  /**
   * Se attiva, la testimonianza sarà mostrata in evidenza
   */
  featured?: boolean | null;
  /**
   * Data della testimonianza (opzionale)
   */
  date?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestisci le comunicazioni di servizio che appaiono nel popup
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "communications".
 */
export interface Communication {
  id: string;
  /**
   * Scuola a cui appartiene questa comunicazione
   */
  school?: (string | null) | School;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  priority: 'low' | 'normal' | 'high' | 'urgent';
  isActive?: boolean | null;
  publishedAt: string;
  expiresAt?: string | null;
  linkedArticle?: (string | null) | Article;
  linkedEvent?: (string | null) | Event;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestisci gli iscritti alle notifiche email delle comunicazioni
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-subscribers".
 */
export interface EmailSubscriber {
  id: string;
  /**
   * Scuola per cui l'utente riceve notifiche
   */
  school?: (string | null) | School;
  /**
   * Indirizzo email per le notifiche (può essere iscritto a più scuole)
   */
  email: string;
  /**
   * Se disattivato, non riceverà più notifiche
   */
  isActive?: boolean | null;
  subscribedAt?: string | null;
  /**
   * Token unico per la disiscrizione
   */
  unsubscribeToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestisci le richieste di registrazione dei genitori in attesa di approvazione
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parent-registrations".
 */
export interface ParentRegistration {
  id: string;
  /**
   * Scuola per cui il genitore sta richiedendo l'accesso
   */
  school?: (string | null) | School;
  /**
   * Stato della richiesta di registrazione
   */
  status: 'pending' | 'approved' | 'rejected';
  parentFirstName: string;
  parentLastName: string;
  /**
   * Verrà utilizzata come username per l'accesso
   */
  parentEmail: string;
  /**
   * Hash bcrypt della password scelta dal genitore
   */
  passwordHash?: string | null;
  childFirstName: string;
  childLastName: string;
  /**
   * Es: "1A", "Sezione Azzurra", ecc.
   */
  childClassroom: string;
  /**
   * ID dell'utente creato dopo l'approvazione
   */
  createdUserId?: string | null;
  /**
   * ID del bambino creato dopo l'approvazione
   */
  createdChildId?: string | null;
  /**
   * Utente che ha approvato la richiesta
   */
  approvedBy?: (string | null) | User;
  /**
   * Data e ora dell'approvazione
   */
  approvedAt?: string | null;
  /**
   * Motivo per cui la richiesta è stata rifiutata
   */
  rejectionReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "child-updates".
 */
export interface ChildUpdate {
  id: string;
  /**
   * Scuola a cui appartiene questo aggiornamento
   */
  school?: (string | null) | School;
  /**
   * Il bambino a cui si riferisce questo aggiornamento
   */
  child?: (string | null) | Child;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  type: 'daily_activity' | 'achievement' | 'note' | 'event';
  /**
   * Foto delle attività svolte
   */
  photos?: (string | Media)[] | null;
  publishedAt: string;
  /**
   * Chi ha creato questo aggiornamento
   */
  author?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parent-appointments".
 */
export interface ParentAppointment {
  id: string;
  /**
   * Scuola
   */
  school?: (string | null) | School;
  /**
   * Il bambino per cui è l'appuntamento
   */
  child?: (string | null) | Child;
  /**
   * Insegnante presente all'appuntamento (opzionale)
   */
  teacher?: (string | null) | Teacher;
  title: string;
  description?: string | null;
  date: string;
  /**
   * Es: "Aula 2A", "Sala Riunioni"
   */
  location?: string | null;
  status: 'scheduled' | 'completed' | 'cancelled';
  /**
   * Note compilate dopo l'incontro
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'schools';
        value: string | School;
      } | null)
    | ({
        relationTo: 'homepage';
        value: string | Homepage;
      } | null)
    | ({
        relationTo: 'privacy-policy';
        value: string | PrivacyPolicy;
      } | null)
    | ({
        relationTo: 'cookie-policy';
        value: string | CookiePolicy;
      } | null)
    | ({
        relationTo: 'chi-siamo';
        value: string | ChiSiamo;
      } | null)
    | ({
        relationTo: 'teachers';
        value: string | Teacher;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'calendar-days';
        value: string | CalendarDay;
      } | null)
    | ({
        relationTo: 'menu';
        value: string | Menu;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'communications';
        value: string | Communication;
      } | null)
    | ({
        relationTo: 'email-subscribers';
        value: string | EmailSubscriber;
      } | null)
    | ({
        relationTo: 'parent-registrations';
        value: string | ParentRegistration;
      } | null)
    | ({
        relationTo: 'child-updates';
        value: string | ChildUpdate;
      } | null)
    | ({
        relationTo: 'parent-appointments';
        value: string | ParentAppointment;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'gallery';
        value: string | Gallery;
      } | null)
    | ({
        relationTo: 'children';
        value: string | Child;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schools_select".
 */
export interface SchoolsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isActive?: T;
  logo?: T;
  lightTheme?:
    | T
    | {
        textPrimary?: T;
        textSecondary?: T;
        backgroundPrimary?: T;
        backgroundSecondary?: T;
      };
  darkTheme?:
    | T
    | {
        textPrimary?: T;
        textSecondary?: T;
        backgroundPrimary?: T;
        backgroundSecondary?: T;
      };
  primaryColor?: T;
  secondaryColor?: T;
  backgroundPrimaryColor?: T;
  backgroundSecondaryColor?: T;
  contactInfo?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  featureVisibility?:
    | T
    | {
        showChiSiamo?: T;
        showBlog?: T;
        showEvents?: T;
        showProjects?: T;
        showCalendar?: T;
        showMenu?: T;
        showDocuments?: T;
        showCommunications?: T;
        showParentsArea?: T;
      };
  subscription?:
    | T
    | {
        plan?: T;
        isTrial?: T;
        expiresAt?: T;
        stripeCustomerId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  school?: T;
  isActive?: T;
  name?: T;
  heroSettings?:
    | T
    | {
        showHero?: T;
        title?: T;
        subtitle?: T;
        fullHeight?: T;
        backgroundImage?: T;
        parallax?: T;
        gradientOverlay?: T;
        bottomDivider?:
          | T
          | {
              enabled?: T;
              style?: T;
              height?: T;
              flip?: T;
              invert?: T;
            };
      };
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              backgroundColor?: T;
              title?: T;
              subtitle?: T;
              fullHeight?: T;
              backgroundImage?: T;
              parallax?: T;
              gradientOverlay?: T;
              buttons?:
                | T
                | {
                    text?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              topDivider?:
                | T
                | {
                    enabled?: T;
                    style?: T;
                    height?: T;
                    flip?: T;
                    invert?: T;
                  };
              bottomDivider?:
                | T
                | {
                    enabled?: T;
                    style?: T;
                    height?: T;
                    flip?: T;
                    invert?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              backgroundColor?: T;
              title?: T;
              limit?: T;
              showViewAll?: T;
              featuredOnly?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              backgroundColor?: T;
              title?: T;
              subtitle?: T;
              image?: T;
              buttons?:
                | T
                | {
                    text?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              backgroundColor?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              backgroundColor?: T;
              title?: T;
              columns?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        fileDownload?:
          | T
          | {
              backgroundColor?: T;
              title?: T;
              description?: T;
              files?:
                | T
                | {
                    file?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              backgroundColor?: T;
              gallery?: T;
              id?: T;
              blockName?: T;
            };
        articleList?:
          | T
          | {
              backgroundColor?: T;
              title?: T;
              limit?: T;
              showViewAll?: T;
              id?: T;
              blockName?: T;
            };
        eventList?:
          | T
          | {
              backgroundColor?: T;
              title?: T;
              limit?: T;
              filter?: T;
              showViewAll?: T;
              id?: T;
              blockName?: T;
            };
        projectList?:
          | T
          | {
              backgroundColor?: T;
              title?: T;
              limit?: T;
              showViewAll?: T;
              id?: T;
              blockName?: T;
            };
        communications?:
          | T
          | {
              backgroundColor?: T;
              title?: T;
              limit?: T;
              priorityFilter?: T;
              showViewAll?: T;
              id?: T;
              blockName?: T;
            };
        teacherList?:
          | T
          | {
              backgroundColor?: T;
              title?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  school?: T;
  isActive?: T;
  name?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-policy_select".
 */
export interface CookiePolicySelect<T extends boolean = true> {
  school?: T;
  isActive?: T;
  name?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chi-siamo_select".
 */
export interface ChiSiamoSelect<T extends boolean = true> {
  school?: T;
  isActive?: T;
  name?: T;
  heroSettings?:
    | T
    | {
        showHero?: T;
        title?: T;
        subtitle?: T;
        fullHeight?: T;
        backgroundImage?: T;
        parallax?: T;
        gradientOverlay?: T;
        bottomDivider?:
          | T
          | {
              enabled?: T;
              style?: T;
              height?: T;
              flip?: T;
              invert?: T;
            };
      };
  content?: T;
  teachersSection?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers_select".
 */
export interface TeachersSelect<T extends boolean = true> {
  school?: T;
  name?: T;
  role?: T;
  subject?: T;
  email?: T;
  bio?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  school?: T;
  title?: T;
  date?: T;
  description?: T;
  location?: T;
  cost?: T;
  cover?: T;
  gradientOverlay?: T;
  gallery?: T;
  addToCalendar?: T;
  sendCommunication?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  school?: T;
  title?: T;
  description?: T;
  cover?: T;
  gradientOverlay?: T;
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-days_select".
 */
export interface CalendarDaysSelect<T extends boolean = true> {
  school?: T;
  title?: T;
  description?: T;
  type?: T;
  cost?: T;
  linkedEvent?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  school?: T;
  name?: T;
  isActive?: T;
  validFrom?: T;
  validTo?: T;
  week1?:
    | T
    | {
        lunedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        martedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        mercoledì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        giovedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        venerdì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        notes?: T;
      };
  week2?:
    | T
    | {
        lunedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        martedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        mercoledì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        giovedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        venerdì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        notes?: T;
      };
  week3?:
    | T
    | {
        lunedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        martedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        mercoledì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        giovedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        venerdì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        notes?: T;
      };
  week4?:
    | T
    | {
        lunedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        martedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        mercoledì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        giovedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        venerdì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        notes?: T;
      };
  generalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  school?: T;
  title?: T;
  description?: T;
  files?:
    | T
    | {
        file?: T;
        title?: T;
        description?: T;
        version?: T;
        featured?: T;
        id?: T;
      };
  order?: T;
  requiresAuth?: T;
  publishedAt?: T;
  expiresAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  school?: T;
  approved?: T;
  isActive?: T;
  authorName?: T;
  role?: T;
  photo?: T;
  content?: T;
  rating?: T;
  featured?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "communications_select".
 */
export interface CommunicationsSelect<T extends boolean = true> {
  school?: T;
  title?: T;
  content?: T;
  priority?: T;
  isActive?: T;
  publishedAt?: T;
  expiresAt?: T;
  linkedArticle?: T;
  linkedEvent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-subscribers_select".
 */
export interface EmailSubscribersSelect<T extends boolean = true> {
  school?: T;
  email?: T;
  isActive?: T;
  subscribedAt?: T;
  unsubscribeToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parent-registrations_select".
 */
export interface ParentRegistrationsSelect<T extends boolean = true> {
  school?: T;
  status?: T;
  parentFirstName?: T;
  parentLastName?: T;
  parentEmail?: T;
  passwordHash?: T;
  childFirstName?: T;
  childLastName?: T;
  childClassroom?: T;
  createdUserId?: T;
  createdChildId?: T;
  approvedBy?: T;
  approvedAt?: T;
  rejectionReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "child-updates_select".
 */
export interface ChildUpdatesSelect<T extends boolean = true> {
  school?: T;
  child?: T;
  title?: T;
  content?: T;
  type?: T;
  photos?: T;
  publishedAt?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parent-appointments_select".
 */
export interface ParentAppointmentsSelect<T extends boolean = true> {
  school?: T;
  child?: T;
  teacher?: T;
  title?: T;
  description?: T;
  date?: T;
  location?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  school?: T;
  title?: T;
  cover?: T;
  gradientOverlay?: T;
  slug?: T;
  content?: T;
  author?: T;
  publishedAt?: T;
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  school?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  school?: T;
  title?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        order?: T;
        id?: T;
      };
  linkedTo?:
    | T
    | {
        type?: T;
        article?: T;
        event?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "children_select".
 */
export interface ChildrenSelect<T extends boolean = true> {
  school?: T;
  firstName?: T;
  lastName?: T;
  fullName?: T;
  dateOfBirth?: T;
  classroom?: T;
  photo?: T;
  enrollmentDate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  schools?: T;
  children?: T;
  firstName?: T;
  lastName?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}