/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    schools: School;
    media: Media;
    articles: Article;
    events: Event;
    teachers: Teacher;
    menu: Menu;
    pages: Page;
    'calendar-days': CalendarDay;
    communications: Communication;
    gallery: Gallery;
    'email-subscribers': EmailSubscriber;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    schools: SchoolsSelect<false> | SchoolsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    teachers: TeachersSelect<false> | TeachersSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'calendar-days': CalendarDaysSelect<false> | CalendarDaysSelect<true>;
    communications: CommunicationsSelect<false> | CommunicationsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    'email-subscribers': EmailSubscribersSelect<false> | EmailSubscribersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Super Admin: accesso globale | School Admin: gestisce la propria scuola | Editor: può modificare contenuti | Viewer: solo lettura
   */
  role?: ('super-admin' | 'school-admin' | 'editor' | 'viewer') | null;
  /**
   * Scuola di appartenenza
   */
  school?: (string | null) | School;
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schools".
 */
export interface School {
  id: string;
  /**
   * Il nome completo della scuola
   */
  name: string;
  /**
   * Identificatore univoco per URL (es: scuola-primaria-roma)
   */
  slug: string;
  /**
   * Dominio personalizzato (es: scuola.example.com) - opzionale
   */
  domain?: string | null;
  /**
   * Logo della scuola
   */
  logo?: (string | null) | Media;
  /**
   * Colore principale del tema
   */
  primaryColor?: string | null;
  /**
   * Colore secondario del tema
   */
  secondaryColor?: string | null;
  /**
   * Colore di sfondo primario del tema
   */
  backgroundPrimaryColor?: string | null;
  /**
   * Colore di sfondo secondario del tema
   */
  backgroundSecondaryColor?: string | null;
  /**
   * Se disattivata, il sito della scuola non sarà accessibile
   */
  isActive?: boolean | null;
  contactInfo?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  settings?: {
    /**
     * Gli utenti possono auto-registrarsi per questa scuola
     */
    allowPublicRegistration?: boolean | null;
    /**
     * Fuso orario della scuola (es: Europe/Rome)
     */
    timezone?: string | null;
    language?: ('it' | 'en' | 'fr' | 'es') | null;
  };
  /**
   * Informazioni sul piano di abbonamento
   */
  subscription?: {
    plan?: ('free' | 'basic' | 'premium' | 'enterprise') | null;
    /**
     * Data di scadenza del piano corrente
     */
    expiresAt?: string | null;
    /**
     * Numero massimo di utenti amministratori
     */
    maxUsers?: number | null;
    /**
     * Spazio di archiviazione massimo in MB
     */
    maxStorage?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Scuola a cui appartiene questo file
   */
  school?: (string | null) | School;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  /**
   * Scuola a cui appartiene questo articolo
   */
  school?: (string | null) | School;
  title: string;
  cover?: (string | null) | Media;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (string | null) | User;
  publishedAt?: string | null;
  /**
   * Collega una galleria di immagini a questo articolo (opzionale)
   */
  gallery?: (string | null) | Gallery;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: string;
  /**
   * Scuola a cui appartiene questa galleria
   */
  school?: (string | null) | School;
  /**
   * Nome identificativo della galleria
   */
  title: string;
  /**
   * Breve descrizione della galleria (opzionale)
   */
  description?: string | null;
  /**
   * Aggiungi le immagini alla galleria
   */
  images?:
    | {
        image: string | Media;
        /**
         * Testo descrittivo per l'immagine (opzionale)
         */
        caption?: string | null;
        /**
         * Numero per ordinare le immagini (più basso = prima)
         */
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Specifica a quale contenuto è collegata questa galleria (opzionale)
   */
  linkedTo?: {
    type?: ('none' | 'article' | 'page' | 'event') | null;
    article?: (string | null) | Article;
    page?: (string | null) | Page;
    event?: (string | null) | Event;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * Scuola a cui appartiene questa pagina
   */
  school?: (string | null) | School;
  title: string;
  /**
   * Es: chi-siamo, contatti, storia
   */
  slug: string;
  /**
   * Testo che appare sotto il titolo nell'hero
   */
  subtitle?: string | null;
  /**
   * Immagine opzionale per l'hero della pagina
   */
  cover?: (string | null) | Media;
  /**
   * Testo principale che appare dopo l'hero
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Aggiungi sezioni personalizzate come call-to-action, team cards, feature grids, ecc.
   */
  blocks?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            image?: (string | null) | Media;
            buttons?:
              | {
                  text: string;
                  href: string;
                  variant?: ('default' | 'secondary' | 'outline' | 'ghost') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            title?: string | null;
            columns?: ('2' | '3' | '4') | null;
            cards?:
              | {
                  title: string;
                  description?: string | null;
                  image?: (string | null) | Media;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardGrid';
          }
        | {
            /**
             * Es: "Documenti Utili", "Moduli da scaricare"
             */
            title?: string | null;
            description?: string | null;
            files?:
              | {
                  /**
                   * PDF, DOC, XLS, o altri documenti
                   */
                  file: string | Media;
                  /**
                   * Se vuoto, usa il nome del file
                   */
                  title?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'fileDownload';
          }
        | {
            /**
             * Seleziona una galleria esistente da mostrare
             */
            gallery: string | Gallery;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
      )[]
    | null;
  /**
   * Se attivo, questa pagina apparirà automaticamente nel menu di navigazione
   */
  showInNavbar?: boolean | null;
  /**
   * Numero per ordinare le pagine nel menu (più basso = prima)
   */
  navbarOrder?: number | null;
  /**
   * Collega una galleria di immagini a questa pagina (opzionale)
   */
  gallery?: (string | null) | Gallery;
  seo?: {
    /**
     * Titolo per i motori di ricerca (se vuoto, usa il titolo della pagina)
     */
    metaTitle?: string | null;
    /**
     * Descrizione per i motori di ricerca (max 160 caratteri)
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  /**
   * Scuola a cui appartiene questo evento
   */
  school?: (string | null) | School;
  title: string;
  date: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  location?: string | null;
  cover?: (string | null) | Media;
  /**
   * Collega una galleria di immagini a questo evento (opzionale)
   */
  gallery?: (string | null) | Gallery;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers".
 */
export interface Teacher {
  id: string;
  /**
   * Scuola a cui appartiene questo insegnante
   */
  school?: (string | null) | School;
  name: string;
  /**
   * Es: Coordinatore, Insegnante di Matematica
   */
  role?: string | null;
  subject?: string | null;
  email?: string | null;
  bio?: string | null;
  photo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestisci i menù stagionali della mensa
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: string;
  /**
   * Scuola a cui appartiene questo menù
   */
  school?: (string | null) | School;
  /**
   * Nome del menù (es. "Menù Autunno 2025", "Menù Inverno 2025")
   */
  name: string;
  /**
   * Solo il menù attivo sarà visualizzato sul sito. Può esserci solo un menù attivo alla volta.
   */
  isActive?: boolean | null;
  /**
   * Data di inizio validità
   */
  validFrom?: string | null;
  /**
   * Data di fine validità
   */
  validTo?: string | null;
  week1?: {
    lunedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    martedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    mercoledì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    giovedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    venerdì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Note o variazioni specifiche per la settimana 1 (opzionale)
     */
    notes?: string | null;
  };
  week2?: {
    lunedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    martedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    mercoledì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    giovedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    venerdì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Note o variazioni specifiche per la settimana 2 (opzionale)
     */
    notes?: string | null;
  };
  week3?: {
    lunedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    martedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    mercoledì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    giovedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    venerdì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Note o variazioni specifiche per la settimana 3 (opzionale)
     */
    notes?: string | null;
  };
  week4?: {
    lunedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    martedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    mercoledì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    giovedì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    venerdì?: {
      isSpecialDish?: boolean | null;
      dishes?:
        | {
            dish: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Note o variazioni specifiche per la settimana 4 (opzionale)
     */
    notes?: string | null;
  };
  /**
   * Note generali valide per tutto il menù (es. informazioni sugli allergeni)
   */
  generalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-days".
 */
export interface CalendarDay {
  id: string;
  /**
   * Scuola a cui appartiene questo evento del calendario
   */
  school?: (string | null) | School;
  title: string;
  description?: string | null;
  type: 'holiday' | 'closure' | 'event' | 'trip';
  /**
   * Costo dell'evento (es. "15€" o "Gratuito")
   */
  cost?: string | null;
  /**
   * Collega un evento per maggiori dettagli
   */
  linkedEvent?: (string | null) | Event;
  startDate: string;
  /**
   * Lasciare vuoto se è un singolo giorno
   */
  endDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestisci le comunicazioni di servizio che appaiono nel popup
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "communications".
 */
export interface Communication {
  id: string;
  /**
   * Scuola a cui appartiene questa comunicazione
   */
  school?: (string | null) | School;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  priority: 'low' | 'normal' | 'high' | 'urgent';
  /**
   * Solo le comunicazioni attive vengono mostrate e inviano notifiche
   */
  isActive?: boolean | null;
  publishedAt: string;
  /**
   * Dopo questa data la comunicazione non verrà più mostrata
   */
  expiresAt?: string | null;
  /**
   * Collega un articolo per maggiori dettagli (opzionale)
   */
  linkedArticle?: (string | null) | Article;
  /**
   * Collega un evento per maggiori dettagli (opzionale)
   */
  linkedEvent?: (string | null) | Event;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestisci gli iscritti alle notifiche email delle comunicazioni
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-subscribers".
 */
export interface EmailSubscriber {
  id: string;
  /**
   * Scuola per cui l'utente riceve notifiche
   */
  school?: (string | null) | School;
  /**
   * Indirizzo email per le notifiche
   */
  email: string;
  /**
   * Se disattivato, non riceverà più notifiche
   */
  isActive?: boolean | null;
  subscribedAt?: string | null;
  /**
   * Token unico per la disiscrizione
   */
  unsubscribeToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'schools';
        value: string | School;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'teachers';
        value: string | Teacher;
      } | null)
    | ({
        relationTo: 'menu';
        value: string | Menu;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'calendar-days';
        value: string | CalendarDay;
      } | null)
    | ({
        relationTo: 'communications';
        value: string | Communication;
      } | null)
    | ({
        relationTo: 'gallery';
        value: string | Gallery;
      } | null)
    | ({
        relationTo: 'email-subscribers';
        value: string | EmailSubscriber;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  school?: T;
  firstName?: T;
  lastName?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schools_select".
 */
export interface SchoolsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  logo?: T;
  primaryColor?: T;
  secondaryColor?: T;
  backgroundPrimaryColor?: T;
  backgroundSecondaryColor?: T;
  isActive?: T;
  contactInfo?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  settings?:
    | T
    | {
        allowPublicRegistration?: T;
        timezone?: T;
        language?: T;
      };
  subscription?:
    | T
    | {
        plan?: T;
        expiresAt?: T;
        maxUsers?: T;
        maxStorage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  school?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  school?: T;
  title?: T;
  cover?: T;
  slug?: T;
  content?: T;
  author?: T;
  publishedAt?: T;
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  school?: T;
  title?: T;
  date?: T;
  description?: T;
  location?: T;
  cover?: T;
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers_select".
 */
export interface TeachersSelect<T extends boolean = true> {
  school?: T;
  name?: T;
  role?: T;
  subject?: T;
  email?: T;
  bio?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  school?: T;
  name?: T;
  isActive?: T;
  validFrom?: T;
  validTo?: T;
  week1?:
    | T
    | {
        lunedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        martedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        mercoledì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        giovedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        venerdì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        notes?: T;
      };
  week2?:
    | T
    | {
        lunedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        martedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        mercoledì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        giovedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        venerdì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        notes?: T;
      };
  week3?:
    | T
    | {
        lunedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        martedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        mercoledì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        giovedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        venerdì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        notes?: T;
      };
  week4?:
    | T
    | {
        lunedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        martedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        mercoledì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        giovedì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        venerdì?:
          | T
          | {
              isSpecialDish?: T;
              dishes?:
                | T
                | {
                    dish?: T;
                    id?: T;
                  };
            };
        notes?: T;
      };
  generalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  school?: T;
  title?: T;
  slug?: T;
  subtitle?: T;
  cover?: T;
  content?: T;
  blocks?:
    | T
    | {
        callToAction?:
          | T
          | {
              title?: T;
              subtitle?: T;
              image?: T;
              buttons?:
                | T
                | {
                    text?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              title?: T;
              columns?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        fileDownload?:
          | T
          | {
              title?: T;
              description?: T;
              files?:
                | T
                | {
                    file?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              gallery?: T;
              id?: T;
              blockName?: T;
            };
      };
  showInNavbar?: T;
  navbarOrder?: T;
  gallery?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-days_select".
 */
export interface CalendarDaysSelect<T extends boolean = true> {
  school?: T;
  title?: T;
  description?: T;
  type?: T;
  cost?: T;
  linkedEvent?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "communications_select".
 */
export interface CommunicationsSelect<T extends boolean = true> {
  school?: T;
  title?: T;
  content?: T;
  priority?: T;
  isActive?: T;
  publishedAt?: T;
  expiresAt?: T;
  linkedArticle?: T;
  linkedEvent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  school?: T;
  title?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        order?: T;
        id?: T;
      };
  linkedTo?:
    | T
    | {
        type?: T;
        article?: T;
        page?: T;
        event?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-subscribers_select".
 */
export interface EmailSubscribersSelect<T extends boolean = true> {
  school?: T;
  email?: T;
  isActive?: T;
  subscribedAt?: T;
  unsubscribeToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}